global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "nest_app"

rule_files:

scrape_configs:
  - job_name: "prod"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api.school-sotvorchestvo.ru"]

  - job_name: "dev"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["45.12.72.204:8081"]

  - job_name: "nest_app"
    metrics_path: /api/metrics
    dns_sd_configs:
      - names: ["nest_app"]
        port: 8081
        type: A
        refresh_interval: 5s